### ISSUE TITLE
Release version is off from filename

### ISSUE THREAD

**Issue by Moburma** [swfans/swars-gfx#1]
The latest gfx release is in file swars-gfx-1_0_1_23.zip, but the version tag is still only 1.0.0.23. This makes the automatic download in the Windows installer fail, as it's looking for https://github.com/swfans/swars-gfx/releases/download/1.0.1.23/swars-gfx-1_0_1_23.zip when the url is actually https://github.com/swfans/swars-gfx/releases/download/1.0.0.23/swars-gfx-1_0_1_23.zip

**Comment by mefistotelis** [comment]
Right, my mistake. I updated the release to use tag 1.0.1.23.

**Comment by Moburma** [comment]
Yep, working fine now
